### ISSUE TITLE
Support currencies specefication

### ISSUE THREAD

**Issue by amir-saadallah** [RSC-Labs/medusa-documents#3]
Some currencies have 3 decimals, the current behaviour is that all currencies are shown in 2 decimal formal which is wrong 
for example with TND currency 
the amount needs to be 123.443 not 1234.43

**Comment by radoslaw-sz** [comment]
hi @amir-saadallah  - thanks for raising this issue. Fortunately, the new version with support of all currencies will be released soon :) I will let you know when ready.

**Comment by radoslaw-sz** [comment]
hi @amir-saadallah  - multicurrency support has been added in version 0.4.0. Please kindly check.

**Comment by amir-saadallah** [comment]
Awesome buddy, dope
